notifications:
  email: false

language: python
python:
  - "2.7"

install:
  - pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.3.0-cp27-none-linux_x86_64.whl
  - pip install pillow

script:
  - tests/run_tests.sh

