language: ruby
rvm:
  - 2.3.3
script:
  - cd site
  - bundle exec jekyll build
deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    name: $GITHUB_USER
    email: $GITHUB_EMAIL
    skip_cleanup: true
    local_dir: _site/
    on:
      tags: false
      branch: master
      repo: monnoroch/generative
